### ISSUE TITLE
Crashes with an Xml parsing related exception if gulpfile.js has been commented out

### ISSUE THREAD

**Issue by joelday** [madskristensen/NpmTaskRunner#11]
After changing gulpfile.js to prepend // to every line, Visual Studio crashed every time it attempted to load the xproj.

(Sorry for the vague info. If it doesn't repro for you folks, I'll see if I can hit it again.)

**Comment by madskristensen** [comment]
I've investigated the issue and there is nothing that can be done from this extension to fix it. The issue lies with the Task Runner Explorer itself and I've opened an internal bug on the VS Web Team to fix it. Closing it here.
