### ISSUE TITLE
TRX error: "Failed to run package.json..."

### ISSUE THREAD

**Issue by scottaddie** [madskristensen/NpmTaskRunner#12]
With this extension installed, I noticed that upon creating a new app via the ASP.NET 5 "StarterWeb" project template, the following error appears in the Task Runner Explorer view of the Output tab in VS 2015 Update 1 (with the ASP.NET 5 RC 1 Update 1 tooling installed):

![npm_scripts_task_runner_error](https://cloud.githubusercontent.com/assets/10702007/12106850/40355526-b329-11e5-81ea-3016385c6dbd.png)

If I close Visual Studio and reopen the same project which I created, the same problem occurs. Also, if I the error appears each time I click the "Show All Files" icon in Solution Explorer. If I uninstall the extension and then create a new project or open this same project, the error doesn't occur. If I add a script with the extension installed, the error doesn't occur. The extension seems to assume that scripts already exist in package.json.

I was able to reproduce this problem on 3 different machines, all with slightly different Visual Studio configurations and extensions.

**Comment by madskristensen** [comment]
I've investigated the issue and there is nothing that can be done from this extension to fix it. The issue lies with the Task Runner Explorer extensibility code and I've opened an internal bug (176952) on the VS Web Team to fix it. Closing it here.

**Comment by scottaddie** [comment]
@madskristensen Thanks for the update!
