### ISSUE TITLE
[feature] Add event "ProjectClose"

### ISSUE THREAD

**Issue by gcnm-pgeil** [madskristensen/NpmTaskRunner#15]
Such an event target would allow lots of use cases. E.g. do I have to update a project-specific metadata file everytime a developer checked out and edited a project and which is used within a larget development workflow process.

Current i wrote a custom VS extension which does that (and als offers a __working__ ProjectOpen event), but having this baked into your great NpmTaskRunner extension would be a more elegant solution.

Many thanks for your work!

**Comment by madskristensen** [comment]
This is a great idea. I've added it to the VS Web Team's backlog. I can't add that event from an extension
