### ISSUE TITLE
Does this allow for specifying node version with tools like NVMw or Nodist?

### ISSUE THREAD

**Issue by airtonix** [madskristensen/NpmTaskRunner#17]

**Comment by scottaddie** [comment]
The extension itself doesn't provide this capability. You can, however, control the versions which are used via the External Web Tools dialog in Visual Studio. Of course, this would apply to everything in Visual Studio. See documentation [here](https://blogs.msdn.microsoft.com/webdev/2015/03/19/customize-external-web-tools-in-visual-studio-2015/).

**Comment by madskristensen** [comment]
Right, though you can't use nvm or nodist, you can make Task Runner Explorer use the version of nodejs that you want.
