### ISSUE TITLE
[Feature request] Bindings Vs build configuration

### ISSUE THREAD

**Issue by GiuseppePiscopo** [madskristensen/NpmTaskRunner#18]
### Installed product versions
- Visual Studio: 2015 Community ed.
- This extension: 1.1.44

### Description
Thanks for this useful extension. Maybe this goes beyond current extension, and it goes straight to Task Runner Explorer, but I'll try here first:

it is quite common for npm script commands to have a *dev* and a *prod* version, especially thinking about bundling, minifying, hot-reloading, and so on. E.g. you find `build-dev` and `build-prod`, as well as `serve-dev` and `serve-prod`.

At a first look those would map nicely with current VS solution build configuration (*Debug*, _Release_, ....), so that e.g.:

* Debug configuration: `build-dev` is bound to _After Build_ binding
* Release configuration: `build-prod` is bound to _After Build_ binding

What do you think about it? Thanks 

PS sorry for cross-posting here and on Visual Studio gallery as well.

**Comment by madskristensen** [comment]
That would be a neat feature, but not one that this extension can provide, unfortunately

**Comment by GiuseppePiscopo** [comment]
Just wondering: is that a matter of not enough time (A), or instead there's no technical way the extension can be made *aware* of current solution configuration (B) ?

**Comment by madskristensen** [comment]
The task bindings system in Task Runner Explorer needs to be made aware of VS configuration. This extension could be, but without the bindings made aware of it too, I wouldn't know how to differentiate between a dev and prod task

**Comment by GiuseppePiscopo** [comment]
Thanks for explaining!

**Comment by tompipe** [comment]
Why not allow multiple sets of bindings, a 'global' one that runs always (as it does now), buit also add additional set of bindings for each build configuration too. 

Its then up to the developer to choose which tasks to bind to each event in each build configuration
