### ISSUE TITLE
[Feature request] Run default npm scripts from Task Runner

### ISSUE THREAD

**Issue by BrainCrumbz** [madskristensen/NpmTaskRunner#20]
### Installed product versions
-  Visual Studio: 2015 Community ed.
- This extension: 1.1.44

### Description
Thinking back, [your comment](https://github.com/madskristensen/NpmTaskRunner/issues/19#issuecomment-198397980) on issue #19 got us thinking:

> Great idea. What do we do if there is a postinstall script but no install? Do we create the install parent node in that case since it has to be executable for the postinstall to work?

At the moment there's no way to run default npm commands from the Task Runner, unless they are actually listed. So e.g. we have defined `start` in our scripts, and we can run it, but e.g. we did not define `install`, but still we can run that from console. 

Maybe it could be worth it to add them to the Runner as well. They'd be some kind of *ghost* items, or *implicit* items, that are listed even if not actually present.

In this scenario, your earlier comment comes back to place: if scripts contains `postinstall`, that would be nested under the *implicit* `install`.

Does that make sense? (For this same release, in case?)

**Comment by BrainCrumbz** [comment]
This would be the full list of default commands: https://github.com/npm/npm/blob/master/lib/run-script.js#L64 , to be executed as `npm <command>` (no `run` needed of course)

**Comment by madskristensen** [comment]
It seems like `version` and `install` are the only two default commands that can always be executed. Should we always add those two to the task list?

**Comment by madskristensen** [comment]
Actually, `version` can't be executed the same way. How about just adding `install` as a permanent task in the list?

**Comment by BrainCrumbz** [comment]
Uhm, *install* and *uninstall* for sure can be run without being listed. One can add custom pre / post commands for those. Don't remember if one can actually declare its own *install* or *uninstall*. 

We'll do some tests on those and on other default commands.

**Comment by madskristensen** [comment]
I've updated the extension with auto-injection of _install_ and _uninstall_ nodes if any post- or -pre command is defined. The new parent _install_ and _uninstall_ nodes cannot be executed - they are used for nesting only. Check it out here http://vsixgallery.com/extension/d7f89ba3-815c-4feb-89b9-68d1654e2138/

**Comment by scottaddie** [comment]
It is possible to declare your own `install` script in `package.json`. Here are a few examples:

1. [https://github.com/scottaddie/webpack-angular-es2015/blob/master/package.json#L13](https://github.com/scottaddie/webpack-angular-es2015/blob/master/package.json#L13)
2. [https://github.com/johnpapa/gulp-patterns/blob/master/package.json#L16](https://github.com/johnpapa/gulp-patterns/blob/master/package.json#L16)

**Comment by madskristensen** [comment]
So if you can declare your own `install`, then what should be the behavior here?

Here's a suggestion:

1. The `install` task node is always created when `preinstall` or `postinstall` is present
2. The `install` task runs `npm run install` when clicked

**Comment by scottaddie** [comment]
@madskristensen I agree with number 2 listed above. As for number 1 in your comment, I would expect `install` to display all the time. If I define my own commands in the `install` script, the npm packages will still be installed. My commands should execute immediately after.

**Comment by scottaddie** [comment]
The `uninstall` command, in my opinion, is another great task to display at all times. It's a nice alternative to hopping out to the command shell and running rimraf.

**Comment by scottaddie** [comment]
It would also be nice if, when right-clicking the `uninstall` task, you see a list of top-level modules installed locally that can be uninstalled. For example, run `npm list --depth=0` at the same level as the package.main file. I would expect to see those packages listed when right-clicking the `uninstall` task. You would ideally have the ability to select multiple modules from the context menu which appears.

**Comment by BrainCrumbz** [comment]
Sorry for being quiet :smile: , trying to recap my thoughts here:

1. as a general rule, npm task runner explorer (TRX) should "follow" the same rationale offered by npm when running scripts. This is so that existing npm users are not "surprised", and so that newcomers can "learn" its usage the right way and can easily move between VS and console.

1. among *default* (so to say) scripts commands, all those that can be **always** run, whether they're in `package.json` or not, should be always listed. This is so that user can always run them from TRX. This would be the case e.g. for `install` and `uninstall`.

1. If there are default commands that can be run **only** if listed in `package.json` (don't know if those exist), then those should appear only if found in json. 

1. If previous case is actually possible, that would leave an open point on what to do when the command is not found, but there's a post- pre- related command. Although this seems a little counter intuitive ... so I'd first check if this can happen at all. Anyway, I'd stick mimicking actual npm behaviour.

**Comment by BrainCrumbz** [comment]
After some quick tests, among *default* scripts:

1. The following can always be run, whether they're actually listed or not:
  * `install`
  * `uninstall`
  * `test`
  * `publish`
  * `restart`
  * `version`, although as @madskristensen mentioned this cannot be launched effectively from TRX, because it would also need an additional `<newversion>` parameter. In this case, one should decide where to show a `pre-` or `postversion` command if found.
  * For each of those, if a command with same name is found, npm will execute that as well
  * For each of those, if a pre- or post- command is found, npm will execute that as well. So npm TRX should nest those under the default nodes.

1. The following can be launched only if actually listed in `package.json`:
  * `start`
  * `stop`
  * Hence, npm TRX should list those under *Default* group only if found. 
  * If they're not found, and some `prestart`, `prestop`, ... is found, one should decide what to do with them in npm TRX. Should they be listed as ordinary *Custom* commands? Or maybe listed among *Default*, under a "disabled" `start`/`stop` node.

**Comment by scottaddie** [comment]
@BrainCrumbz In response to the 2nd item in your response immediately above, I would expect to see a "disabled" `start` / `stop` node. This would serve as a hint to the developer that a `start` and/or `stop` hook exists and can be defined in the `package.json` file.

**Comment by BrainCrumbz** [comment]
Totally agree. Sticking with that proposal, it remains yet to decide what to do with `pre`\`postversion` commands if found, as at the moment there's no way to effectively run `version` from *npm TRX*

**Comment by madskristensen** [comment]
I've just made the modifications discussed here.

Consider this package.json file:

```json

{
	"dependencies": {
		"knockout": "3.4.0"
	},
	"devDependencies": {
		"jquery": "2.2.2"
	},
	"scripts": {
		"foo": "echo foo",
		"prefoo": "echo foo",
		"install": "echo install",
		"postinstall": "echo postinstall",
		"preinstall": "echo preinstall",
		"posttest": "echo post test",
		"prestart": "",
		"preuninstall": "echo preuninstall",
		"postuninstall": "echo postuninstall",
		"preversion": "echo preversion"
	}
}
```
It will produce this in TRX:

![untitled](https://cloud.githubusercontent.com/assets/1258877/13923349/7f2243b6-ef3d-11e5-91a3-05d0f49dd147.png)

`version` is created because `perversion` exist, but it is readonly (TRX makes readonly nodes bold)

**Comment by BrainCrumbz** [comment]
Cool, I'll install that now. While looking at [former commit](https://github.com/madskristensen/NpmTaskRunner/commit/a2923204ec20a1eb3293250caa59a064756b875b), shouldn't `test` be moved from `DEFAULT_TASKS` to `ALWAYS_TASKS`?
Thanks!

**Comment by madskristensen** [comment]
`test` was shown always, but since it doesn't do anything, I thought it just added noise to always show it

**Comment by BrainCrumbz** [comment]
I see. "Seems legit"

**Comment by scottaddie** [comment]
@madskristensen I installed the latest version of the extension. One question for you. When binding the uninstallation of a specific npm module to a Visual Studio event, I see this:

![bindings](https://cloud.githubusercontent.com/assets/10702007/13925607/f403fd50-ef56-11e5-9301-74002ed9a370.png)

Does it make sense to prepend the package name (`babel-polyfill`) appearing under the **Before Build**/**package.json** node with something like "uninstall: "? Displaying the package name by itself doesn't make it clear that `uninstall` will be invoked.

**Comment by madskristensen** [comment]
@scottaddie That's a good idea

**Comment by scottaddie** [comment]
@madskristensen If the npm modules haven't yet been installed in the project, it would be nice to disable the `uninstall` node in the extension. Thoughts? It could be as simple as checking for the presence of the `node_modules` folder.

**Comment by BrainCrumbz** [comment]
@scottaddie On this last one, npm TRX could also stick with what npm does out of the box: you're allowed to uninstall something, worst case if that's not installed you just get some error explaining situation. Just thinking...

**Comment by scottaddie** [comment]
@BrainCrumbz Honestly, I could go either way with this one. I definitely see your point.

@madskristensen While you're in there, I also believe that the string array declared [here](https://github.com/madskristensen/NpmTaskRunner/blob/master/src/TaskRunner/TaskParser.cs#L11) shouldn't contain `bundleDependencies`, `bundledDependencies`, or `peerDependencies`. The [documentation for `uninstall`](https://docs.npmjs.com/cli/uninstall) only mentions CLI flags for `dependencies`, `devDependencies`, and `optionalDependencies`.

**Comment by madskristensen** [comment]
I tried uninstalling a package specified in `peerDependencies` and it failed, so I've removed the `peerDependencies` and `bundleDependencies` as suggested.

Let's keep the `uninstall` node even if node_modules folder is missing. The TRX will not reload the task after an install, only when package.json has been modified, so it will have false negatives if we hide it

**Comment by scottaddie** [comment]
@madskristensen Here's one other potential problem I noticed. The user shouldn't be allowed to bind, for example, the entire `dependencies` node and 1 of its children (e.g., `babel-polyfill`) to the same Visual Studio event. Here's a screenshot to clarify:

![bindings](https://cloud.githubusercontent.com/assets/10702007/13933571/d6894c9c-ef7b-11e5-99e5-c6f16dd60d20.png)

Since `dependencies` is already attached to the binding, `babel-polyfill` would be accounted for in the uninstall which runs during the "Before Build" event. How should this be handled?

**Comment by madskristensen** [comment]
There is no API in TRX to handle that easily. I think this represents an edge case only and I'm not convinced that we should spend time coming up with a fix at this point in time

**Comment by BrainCrumbz** [comment]
Only throwing our 2c on this: 

maybe installing/ uninstalling single packages can be considered somehow a less frequent need, so one could argue whether the single dependencies are needed at all. Of course, this might be also "personal".

For one thing, I cannot find a useful example right now to have install/uninstall bound to some VS build events. By comparison with NuGet, it sounds like performing a NuGet package install/uninstall in relation to some build event, and I cannot see usefulness of this ... I'm guess I'm missing something from the big picture.   

Install/uninstall are more related to project setup, than build events, so are somehow more "stable". Comparatively, it might be more useful to provide some kind of project-wide *update* / *upgrade*, e.g. similar to `npm update`, but then again, there should be a reasonable need for this.

**Comment by scottaddie** [comment]
> maybe installing/ uninstalling single packages can be considered somehow a less frequent need, so one could argue whether the single dependencies are needed at all. Of course, this might be also "personal".

I agree that uninstalling individual packages is a less frequent need; however, it's useful for members of a team who aren't familiar with the inner workings of npm but want to uninstall a particular dependency which is no longer needed. This would save them from dropping out to the command shell and potentially messing something up.

> For one thing, I cannot find a useful example right now to have install/uninstall bound to some VS build events. By comparison with NuGet, it sounds like performing a NuGet package install/uninstall in relation to some build event, and I cannot see usefulness of this ... I'm guess I'm missing something from the big picture.

> Install/uninstall are more related to project setup, than build events, so are somehow more "stable". Comparatively, it might be more useful to provide some kind of project-wide update / upgrade, e.g. similar to npm update, but then again, there should be a reasonable need for this.

As for the event binding of `install` and `uninstall`, I tend to agree with you that it's probably not needed. I chose that as a quick example for testing purposes, without putting much thought into it.

**Comment by BrainCrumbz** [comment]
> This would save them from dropping out to the command shell and potentially messing something up.

I tend to agree on this as well. I don't know if npm TRX can disable binding for some particular nodes: in that case, I'd say better to disable binding from whole install/uninstall subtrees.

**Comment by scottaddie** [comment]
@madskristensen I have another idea related to this issue. Per the [docs](https://docs.npmjs.com/cli/publish), a publish will fail if the `package.json` file's `private` property is set to `true`. Here's an example of where that property is being set in the ASP.NET 5 / Core StarterWeb project template: https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/package.json#L4.

Is there any interest in disabling or removing the `publish` node when the `private` property is set to `true`? Leaving it in place in this scenario would always result in a failure. Why display an option to the user that is guaranteed to result in failure?

**Comment by madskristensen** [comment]
@scottaddie Publish is one of those things that I doubt anyone will ever invoke from TRX. But if they do, don't you think they want to see the error message stating that it can't publish a package marked "private"?

**Comment by BrainCrumbz** [comment]
You could release extension as modified recently, and see as it goes, when you get further feedbacks from users.

**Comment by madskristensen** [comment]
@BrainCrumbz  just did

**Comment by scottaddie** [comment]
@madskristensen Tough to say. I would invoke it from the command shell, but of course there are many other user personas out there. I am very interested to see the feedback from the latest enhancements.

**Comment by madskristensen** [comment]
I'm closing this issue since it was added to the latest release
