### ISSUE TITLE
Rename extension to "NPM Task Runner"?

### ISSUE THREAD

**Issue by madskristensen** [madskristensen/NpmTaskRunner#23]
It doesn't sound very smooth to have both "scripts" and "task" in the name of this extension. How about we rename it to one of these:

1. NPM Task Runner
2. NPM Scripts Runner

**Comment by scottaddie** [comment]
Option 1 allows this extension to scale beyond just scripts, should that need ever arise. That would be my choice.

While we're at, can npm be all lowercase? This would make the casing consistent with what the `package.json` item template uses.

**Comment by madskristensen** [comment]
With lower case "npm" it looks a bit weird: **npm Task Runner**?

**Comment by scottaddie** [comment]
I agree that it does look a bit strange. Just figured I'd throw the idea out there and get your opinion.
