### ISSUE TITLE
Why package.json private: true causes an issue, (plus 'Defaults' and 'Custom' views)

### ISSUE THREAD

**Issue by JonPSmith** [madskristensen/NpmTaskRunner#26]
### Installed product versions
- Visual Studio: VS2015 Professional, Update 2
- This extension: 1.3.59

### Description

I have been using your npm task runner successfully for a week or two with a number of custom commands, like webpack build. All has been fine, but I added a new project with a different package.json file and one of the commands won't work. The steps are given below.

*Note: The solution will go with a long article I am writing and as such is open-source the actual code can be found at [JonPSmith/AspNetReactSamples, ReactTests](https://github.com/JonPSmith/AspNetReactSamples/tree/master/ReactTests).*

A second minor issue, but one that I would also like to fix if I can, is that the Task Runner Explorer (TRE) window does not look the way you describe it, as it has a **Default** and **Custom** section (see point 2 below). It would be create to only have the scripts I have installed, especially for people who want to try it.

### Steps to recreate
1. Add the following code to my [package.json](https://github.com/JonPSmith/AspNetReactSamples/blob/master/ReactTests/package.json) file:

```javascript
  "scripts": {
    "test": "karma start",
    "mytest": "karam start"
  },
```

2. Then when I look in the TRE window I see:

- package.json
  - **Defaults**
    - install
    - publish
    - restart
    - test
  - **Custom**
    - mytest

3. If I run `test` then it works, with the following log
```
> cmd.exe /c npm run test --color=always
> reacttests@1.0.0 test C:\Users\Jon\Documents\Visual Studio 2015\Projects\AspNetReactSamples\ReactTests
> karma start
... karma output here....
```

4. If I run `myTest` it fails with the following log

```
> cmd.exe /c npm run mytest --color=always
> reacttests@1.0.0 mytest C:\Users\Jon\Documents\Visual Studio 2015\Projects\AspNetReactSamples\ReactTests
> karam start
'karam' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "mytest" "--color=always"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! reacttests@1.0.0 mytest: `karam start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reacttests@1.0.0 mytest script 'karam start'.
... etc.
```

### Notes

In the solution [JonPSmith/AspNetReactSamples](https://github.com/JonPSmith/AspNetReactSamples) the project [ReactWebPack.MVC5](https://github.com/JonPSmith/AspNetReactSamples/tree/master/ReactWebPack.MVC5) works fine, but the project [ReactTests](https://github.com/JonPSmith/AspNetReactSamples/tree/master/ReactTests) **does not**. I can't see any difference in what I am doing. 

Your help would be appreciated.

**Comment by JonPSmith** [comment]
OK, I found what is different between the two package.json files that fixes this.

If I remove line `"private": true` from the package.json then it works!

That's fine and I will continue like that, but for my own education I would like to know why as the default is for `"private": true`. 

It would also be great to get rid of the **Defaults** if I can, especially for the article.

**Comment by madskristensen** [comment]
It has nothing to do with `private:true`. You made a typo by calling it *karam* instead of *karma*

**Comment by JonPSmith** [comment]
Doh! Really sorry to have wasted your time. I should have seen that!

**Comment by madskristensen** [comment]
No worries :)
