### ISSUE TITLE
wrong architecture (x86) on windows x64

### ISSUE THREAD

**Issue by OneCyrus** [madskristensen/NpmTaskRunner#27]
on a windows x64 installation the extension opens a x86 process (probably because of the x86-only Visual Studio). This causes some problems with some packages as they use the architecture to determine which binaries should be installed and loaded. (e.g. node-sass) 

the extensions should always use x64 on a x64 OS.

**Comment by madskristensen** [comment]
This extension doesn't decide which architecture of node.js to use. That's specified in the External Tools section in VS. See this https://blogs.msdn.microsoft.com/webdev/2015/03/19/customize-external-web-tools-in-visual-studio-2015/

**Comment by OneCyrus** [comment]
i've only node x64 installed on my system. i guess it's only about the environment variable and not about the actual node.exe.

doesn't this line start a x86 cmd.exe? https://github.com/madskristensen/NpmTaskRunner/blob/master/src/TaskRunner/TaskRunnerProvider.cs#L138

**Comment by madskristensen** [comment]
Visual Studio 2015 ships with node.exe 32bit and that's what Task Runner Explorer uses by default unless you change the External Tools like the blog post I linked to shows.
