### ISSUE TITLE
Background tasks not showing output

### ISSUE THREAD

**Issue by brianchance** [madskristensen/NpmTaskRunner#30]
### Installed product versions
Visual Studio: 2015 Professional Update 3 (same behavior on Update 2)
NPM Task Runner: 1.3.62

### Description
I am using webpack with the [awesome-typescript-loaders](https://github.com/s-panferov/awesome-typescript-loader) "forkChecker" feature. In watch mode, this runs the typescript checks in a background thread, then outputs any errors to the console. In the task runner window, the errors never show...

![image](https://cloud.githubusercontent.com/assets/1154287/16453591/f843d1c2-3dd2-11e6-8ff4-ede4530dd122.png)

### Expected behavior
When run from the command line, it produces this output. (the error is in a horrible red)
![image](https://cloud.githubusercontent.com/assets/1154287/16453657/430ee7f0-3dd3-11e6-9868-129e65f115b8.png)

### Steps to recreate
[angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter) uses awesome typescript loader. To get an error, just remove a comma from an import and save. so, in src/main.browser.ts change 
`import { ENV_PROVIDERS, decorateComponentRef } from './platform/environment';` 
to
`import { ENV_PROVIDERS decorateComponentRef } from './platform/environment';`

**Comment by scottaddie** [comment]
@brianchance This is a bug in Task Runner Explorer itself, as described here: https://github.com/aspnet/Tooling/issues/600. I have the same problems when using certain Webpack loaders/plugins.

**Comment by madskristensen** [comment]
Errors and warnings should be piped to the TRX correctly in the just-released ASP.NET Core tooling Preview 2

**Comment by brianchance** [comment]
Thanks all, I will install the update when it comes out.

**Comment by madskristensen** [comment]
It is out already. Get it here https://www.microsoft.com/net/download#tools

**Comment by brianchance** [comment]
That did the trick. Only issue now is how webpack uses the --progress switch. In the task runner, the percentages do not overwrite the line, just append to output. Not really necessary so just turning it off.

**Comment by scottaddie** [comment]
@brianchance That's another feature Task Runner Explorer doesn't support. I've mentioned it to Mads in the past, so I know his team is well aware.
