### ISSUE TITLE
[Feature Request] Pre build failures not failing the build

### ISSUE THREAD

**Issue by macromaniac** [madskristensen/NpmTaskRunner#32]
### Installed product versions
- Visual Studio: [2015 Community 14.0.25425.01 Update 3]
- This extension: [1.3.67]

### Description
When the pre build step fails the build still continues normally. I believe the build should be marked as having failed if the pre build step fails.

### Steps to recreate
This is a feature request, but here we go:
1. add a script "thiswillfail": "asdkljalksjdl" to the scripts part of package.json
2. declare the script as a pre-build step
3. build the project (Ctrl b)
4. The projects build will say "success", despite a failed script

If a pre build step fails its usually pretty important to running the project. I think it would be nice if the build was tagged as failed, if it isn't too difficult to add. The way it is now I have to be tabbing through all the prebuild scripts wondering why my application bundled incorrectly. This functionality would match  visual studio's prebuild/postbuild feature for batch scripts within regular projects.

If a user prefers the older functionality he/she could  "thiswillnotfail": "asdkljalksjdl || true" to supress the error message.

**Comment by madskristensen** [comment]
This is on the backlog of the VS Web Team. This extension cannot provide that functionality, unfortunately.
