### ISSUE TITLE
running from taskrunner provide error, not from command line 

### ISSUE THREAD

**Issue by tbuffryslb** [madskristensen/NpmTaskRunner#33]
### Installed product versions
- Visual Studio: [ 2015 Professional]
- Nodejs v6.2.0
- npm v3.8.9
- This extension: [1.3.69]

### Description
https.get(path, (resHttps) => {
                                ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

### Steps to recreate
1. create a app.js with such code : https.get(path, (resHttps) => {
2. run from commond line => works
3. run from visual studio task runner => errors

**Comment by scottaddie** [comment]
@tbuffryslb Did you already move the $(PATH) entry in the External Web Tools dialog, so that the correct version of npm is being used by Visual Studio? Here's a blog post discussing how:

https://blogs.msdn.microsoft.com/webdev/2015/03/19/customize-external-web-tools-in-visual-studio-2015/

**Comment by tbuffryslb** [comment]
Thank you very much for your rapid response, it solved my issue.

Regards,
