### ISSUE TITLE
Running gcloud preview app deploy

### ISSUE THREAD

**Issue by tbuffryslb** [madskristensen/NpmTaskRunner#34]
### Installed product versions

Visual Studio: [ 2015 Professional]
Nodejs v6.2.0
npm v3.8.9
This extension: [1.3.69]

### Description
on package.json : 
add "deploy": "gcloud preview app deploy"
run deploy task ( with or without verbose )

into a command line window the script is asking for input ( and I need to enter "yes" ) but in the task runner, the script is running without showing any inputs, so the script is waiting for an infinite time ..

### Expected behavior
Could we show the imput request from console ? and if possible add the possibility to respond

**Comment by madskristensen** [comment]
Can the gcloud not be called with a _--silent_ argument or similar so you don't need to manually add input? The Task Runner Explorer doesn't allow for manual input and that can't be fixed by this extension

**Comment by tbuffryslb** [comment]
found a workaround : "echo y | gcloud preview app deploy" is providing the user input "y"
problem solved
