### ISSUE TITLE
Would it be easy to make a version of this for Yarn?

### ISSUE THREAD

**Issue by MiguelAlho** [madskristensen/NpmTaskRunner#38]
Wondering : are considering anything like this for Yarn? Would be nice to have the same thing in VS, but simply calling Yarn instead of NPM. This would enable, for instance, calling `yarn install` binded to "project open" in Visual Studio.

**Comment by madskristensen** [comment]
Yes, someone already forked this project and released a Yarn extension to the VS gallery
