### ISSUE TITLE
Yarn support

### ISSUE THREAD

**Issue by madskristensen** [madskristensen/NpmTaskRunner#39]
When a _yarn.lock_ or _.yarnclean_ file exist in the same directory as package.json, the extension should automatically switch to call the Yarn CLI instead of calling npm

**Comment by scottaddie** [comment]
@madskristensen Let me know if you're looking for some help with this one. I'd be willing to give it a shot.

**Comment by madskristensen** [comment]
Please go ahead. I don't have the time to look at this for the next couple of weeks, so any help would be appreciated :)

**Comment by scottaddie** [comment]
@madskristensen I'm on it

**Comment by scottaddie** [comment]
@madskristensen I've finished my testing and pushed the changes necessary for Yarn CLI support. Take a look, and let me know what you think.

**Comment by madskristensen** [comment]
This looks great!! Thanks for taking a stab at this. I'll try it out shortly

**Comment by madskristensen** [comment]
Dude, this works beautifully. So cool!!!

**Comment by scottaddie** [comment]
@madskristensen It was a pleasure to work on. Now I can put this to use at work.

**Comment by madskristensen** [comment]
Very cool

**Comment by madskristensen** [comment]
The Verbose command flag `-d` doesn't work with yarn

**Comment by scottaddie** [comment]
Good catch. What's the best way to get the `configPath` value from within `TaskRunnerProvider.Options`? TRX core must be determining that and providing it to methods like `TaskRunnerProvider.ParseConfig`.

**Comment by madskristensen** [comment]
Perhaps pass an empty string instead of the `-d` in the Option. Then in the task execution code we can check if the option is enabled and then append it ourselves

**Comment by scottaddie** [comment]
It seems like I'd need to hook into something like TaskRunnerNode's Invoke method to append the option. Did you have something else in mind when you said "task execution code"?

**Comment by madskristensen** [comment]
That's what i meant

**Comment by scottaddie** [comment]
@madskristensen Pushed the commit. Give it a try now.
