### ISSUE TITLE
Locate task that uses require-dir

### ISSUE THREAD

**Issue by jmvtrinidad** [madskristensen/NpmTaskRunner#41]
### Installed product versions
- Visual Studio: [example 2013 Ultimate]
- This extension: [example 1.1.21]

### Description
Add support for gulp task using `require-dir` just like this example in [aurelia](https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-typescript/gulpfile.js).

### Steps to recreate
N/A

### Current behavior
N/A

### Expected behavior
To be able to locate all task using `require-dir`.

**Comment by madskristensen** [comment]
@scottaddie Any idea how to go about supporting this scenario?

**Comment by scottaddie** [comment]
@madskristensen It seems like this is a Gulp-centric enhancement. Doesn't it belong on the product backlog for TRX itself?

**Comment by madskristensen** [comment]
@scottaddie Of course. Yes, you are right. It is to do with the built-in Gulp task runner and not this extension. Closing here and opening bug on VS Web Team

**Comment by jmvtrinidad** [comment]
Hi @scottaddie, what do you mean by **Gulp-centric**?.

Hi @madskristensen, Can you guide me more about opening bug on VS Web Team?
Thanks.

**Comment by scottaddie** [comment]
@jmvtrinidad I mean that anything involving Gulp is handled in Task Runner Explorer itself. This extension just focuses on npm and Yarn commands/scripts.

**Comment by jmvtrinidad** [comment]
@scottaddie Thanks for clarifying. I guess I'm using [Task Runner Explorer](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.TaskRunnerExplorer) by @madskristensen .
