### ISSUE TITLE
Run ES6

### ISSUE THREAD

**Issue by hamed-farag** [madskristensen/NpmTaskRunner#45]
### Installed product versions
- Visual Studio: 2015 Professional Update 3
- This extension: 1.4.81

### Description
I Have run.js file written with ES6 and I have the following issue
![ussie](https://cloud.githubusercontent.com/assets/5382471/21979574/1579cf7c-dbe8-11e6-968c-c2e380138895.png)

**Comment by scottaddie** [comment]
@hamed-farag The error indicates that Visual Studio is attempting to use Node v0.10.31, which is very old. Please try modifying the _External Web Tools_ settings in VS 2015 as follows:
1. **Tools** --> **Options...** --> **Projects and Solutions** --> **External Web Tools**
2. Move the `$(PATH)` entry up to the 2nd position in the list
3. Click OK, and try running the task again
