### ISSUE TITLE
Task runner fails with ES6 code

### ISSUE THREAD

**Issue by crodriguezvega** [madskristensen/NpmTaskRunner#48]
### Installed product versions
- Visual Studio: 2015 Professional Update 3
- This extension: 1.4.81

### Description
I am trying to set up a Vue.js application with Webpack on Visual Studio 201 and I would like to run NPM tasks using this runner.

### Steps to recreate
1. Create a Vue.js application using the Webpack template; follow the steps [here](https://github.com/vuejs-templates/webpackl).
2. Create an empty ASP.NET 4.5.2 web project and add the files created in step number 1.
3. Run the dev task from the task runner.

### Current behavior
When I run an NPM script from the task runner it fails because it cannot recognize some code written with the ES6 syntax. It is basically the same problem as reported [here](http://stackoverflow.com/questions/40019957/visual-studio-npm-task-runner-fails-but-running-task-outside-of-vs-runs-fine).

### Expected behavior
It should run the task. If I run the NPM task from the command line it works fine.

**Comment by scottaddie** [comment]
See my suggestion to fix it here: https://github.com/madskristensen/NpmTaskRunner/issues/47

**Comment by crodriguezvega** [comment]
That solved it. Thank you so much!
