### ISSUE TITLE
Build fails until Task Runner Explorer is opened in Visual Studio 2017

### ISSUE THREAD

**Issue by RobinHSanner** [madskristensen/NpmTaskRunner#56]
### Installed product versions
- Visual Studio: Visual Studio 2017
- This extension: 1.4.81

### Description
Given:
- VS 2017 solution with node.js project
- npm task runner is configured to run install on build
- second project with a dependency (via VS solution) on the node.js project
- Clone (note at this time there will not be a node_modules directory
- Build.  Build fails with error: Build:Cannot find type definition file for 'node'.
- Click 'Task Runner Explorer' tab
- Do build again and now NpmTaskRunner runs npm install and everything is fine

### Current behavior
have to click on 'Task Runner Explorer' tab in Visual Studio in order for build to succeed

### Expected behavior
Shouldn't have to click the tab housing 'Task Runner Explorer' for it to properly run on build

**Comment by georgekolb** [comment]
You are missing the following file: C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\WebApplicationsMicrosoft.WebApplication.targets
Create the necessary folders down to the above and copy the file from C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\WebApplications\Microsoft.WebApplication.targets

**Comment by RobinHSanner** [comment]
That was in fact missing, thank you.  Is the task runner install supposed to position that or was it something else?
