### ISSUE TITLE
Task runner brings it's own (outdated) node and npm 

### ISSUE THREAD

**Issue by michaelbleterman** [madskristensen/NpmTaskRunner#58]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.4.81
-Globally installed node.js 8.9.4

### Description
One of the projects configured to run npm install at BeforeBild script
It fails as it runs with outdated node and npm from it's internal directory rather than globally installed one:
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\\\node\\node" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--color=always"
npm ERR! cwd D:\Projects\5.2.0\ProWebAPI
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.9

Please either update embedded node.js version, allow to upgrade it or just use globally installed one.

**Comment by scottaddie** [comment]
@michaelbleterman See my suggestion to fix it here: https://github.com/madskristensen/NpmTaskRunner/issues/47
