### ISSUE TITLE
Can't recompile through task runner explorer

### ISSUE THREAD

**Issue by vishnutsivan** [madskristensen/NpmTaskRunner#61]
![image](https://user-images.githubusercontent.com/18438320/39031397-835f1f4a-4485-11e8-845c-2654d75fdabe.png)

In Task Runner Explorer _compilerconfig.json->All files->Run_ only compile files. How can I set to re-compile all files?

**Comment by scottaddie** [comment]
@vishnutsivan You'll want to post the issue in the following repo instead: https://github.com/madskristensen/WebCompiler
