### ISSUE TITLE
Package.json not updating on save

### ISSUE THREAD

**Issue by macromaniac** [madskristensen/NpmTaskRunner#7]
Howdy,

I am using the 2015 community edition of visual studio and have version 1.0.21 of "NPM Scripts Task Runner".

Currently package.json doesn't update on save. It only updates if I restart visual studio.

**Comment by madskristensen** [comment]
You can click the refresh button in Task Runner Explorer. Does that not work?

**Comment by macromaniac** [comment]
I tried it and no it didn't. I should have mentioned that in retrospect.

**Comment by macromaniac** [comment]
ex: https://www.youtube.com/watch?v=Q6KlEJ-FXSQ

**Comment by madskristensen** [comment]
Ahh, I know what the issue is. I'll fix it

**Comment by madskristensen** [comment]
Note to self, this is due to the caching issue with the TRX API and I need to do the same trick as in the Command Task Runner extension
