### ISSUE TITLE
This should ship with Web Tools like grunt / gulp task runners

### ISSUE THREAD

**Issue by SoonDead** [madskristensen/NpmTaskRunner#8]
This one is way more essential than grunt or gulp.

Being less requested than grunt / gulp is partially the new ASP.NET template's fault as it configures super simple one liner jobs (like clean) by gulp instead of defining an npm script.

**Comment by madskristensen** [comment]
It's on the Web Teams backlog. Closing here since I (as a third party extension author) can do nothing about it.
