### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by dangrussell** [madskristensen/NpmTaskRunner#80]
### Installed product versions
- Visual Studio Enterprise 2019 (Version 16.7.7)
- This extension: 1.4.90 (latest available)

### Description
It's too bad that this very useful extension seems to be abandoned.

- no new versions for 2 years
- no substantial updates for 4 years
- last release predates VS 2019
- link to "nightly build" from README is broken
- these major issues and more are unaddressed:
	- "Project Open" bindings don't work
	- Breaks JSON syntax in package.json file when removing bindings
	- "Before Build" operations never complete or don't run in parallel so build never continues

It's still referred to in official Microsoft docs: https://docs.microsoft.com/en-us/visualstudio/javascript/compile-typescript-code-npm?view=vs-2019#automate-build-tasks

**Comment by jwbats** [comment]
Is this the repo for [Task Runner Explorer](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.TaskRunnerExplorer) on the VS Marketplace?

For me, it's stopped working. It's probably incompatible with a recent VS update. No more task configurations are found.

I'd love it if it would get fixed. Now I have to run these commands manually, in a terminal outside my VS.

**Comment by madskristensen** [comment]
No, the Task Runner Explorer (TRE) itself is built into Visual Studio. There are just extensions that extends TRE

**Comment by jwbats** [comment]
Yeah, I just found that out as well. I also seem to have task runner extensions and repos mixed up.

I'll just report the problem via VS Feedback.

**Comment by jwbats** [comment]
My issue submission:

https://developercommunity.visualstudio.com/content/problem/1257429/npm-task-runner-no-longer-working.html

**Comment by alex-jitbit** [comment]
So, can we have an answer if this is abandoned or not? It's OK if it is, just need to know.

The only reason my company stays away from npm-runner (and uses more old-school grunt/gulp) is because it's unclear whether this project has any future and/or official support form MS.

PS. although I guess even being an "official" MS product doesn't mean it can't be abandoned - just look at SignalR ;)

**Comment by madskristensen** [comment]
@alex-jitbit I still take pull requests and will publish new versions, but I don't actively work on this project beyond that.

**Comment by jwbats** [comment]
@alex-jitbit

> The only reason my company stays away from npm-runner (and uses more old-school grunt/gulp) is because it's unclear whether this project has any future and/or official support form MS.

You can run your npm tasks in any terminal. VS has an in-built terminal as well. It might even be possible to have it start a task on startup.

NPM Task Runner only brings a little bit of added convenience. It's not mission critical.

**Comment by alex-jitbit** [comment]
@jwbats I know I can do everything manually :) but that's not how things should work. I need everything to happen automatically on project load, and I need the settings to propagate to other team members (and to CI/CD servers) seamlessly by just doing a `git pull`

**Comment by jholland918** [comment]
FYI - I updated to Visual Studio 16.9.2 and the npm task runner project open bindings are now working for me.

**Comment by jwbats** [comment]
For me as well.

**Comment by dangrussell** [comment]
Thank you for the recent updates!
