### ISSUE TITLE
Can't open Task Runner Explorer pane in VS 2022

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [madskristensen/NpmTaskRunner#82]
### Installed product versions
- Visual Studio: Visual Studio Enterprise 2022 Preview 2.0
- This extension: 1.4.96

### Description
When I try to open the Task Runner Explorer, nothing happens.

### Steps to recreate
1. In VS 2022, Click View -> Other Windows -> Task Runner Explorer
2. On my computer, nothing happens
3. Pressing Ctrl+Alt+Backspace also does not cause the Task Runner Explorer pane to appear

Not sure what other information I can provide that might be useful 🙂  Maybe some logs?

**Comment by FreeFrags** [comment]
Unfortunately I have the same issue.

**Comment by madskristensen** [comment]
@sayedihashimi is there a known issue with TRX in Preview 2?

**Comment by sayedihashimi** [comment]
@jimmylewis?

**Comment by jimmylewis** [comment]
Confirmed this is an issue in Preview 2.  I have a PR out to fix it for Preview 3.

**Comment by aszalacinski** [comment]
What's weird is that a co-worker of mine is having the issue but I am not... he is able to open the Task Runner by right clicking on the package.json file and selecting Task Runner from there.

**Comment by jwbats** [comment]
Thanks for the tip, @aszalacinski. It works for me, too. That's a nice workaround for the time being.

**Comment by Bosch-Eli-Black** [comment]
@jimmylewis Has your PR been removed?

**Comment by Bosch-Eli-Black** [comment]
I've upgraded to VS 2022Preview 3 and now I can successfully open the Task Runner Explorer window but it doesn't recognize my package.json file, so now tasks are shown XD

Can anyone else confirm?

**Comment by jwbats** [comment]
Happens to me, too. Sometimes, the tasks don't show. But you can click the refresh icon to make'em show up.

My tasks **do** automatically start running, after upgrading to preview 3.

**Comment by ascott18** [comment]
This worked for me in preview 4, but after upgrading to preview 5 it now crashes VS entirely (crash to desktop).

**Comment by Sjark** [comment]
Crashes on startup for me too in latest preview.

**Comment by madskristensen** [comment]
Test the [new version for VS 2022](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.NpmTaskRunner64) and let me know if it works for you.

**Comment by itniels** [comment]
@madskristensen still crashes on startup unfortunately

**Comment by madskristensen** [comment]
I opened a bug on the Task Runner Explorer (TRX). I think it is an issue that any extension to TRX will encounter.

**Comment by jwbats** [comment]
The [official extension page](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.NPMTaskRunner) says we're still on v1.4.97, even though the last update was on October 19th.

Visual Studio isn't showing any available updates on the NPM Task Runner. Or any other extension, for that matter.

Where's v1.5.99 then?

**Comment by madskristensen** [comment]
@patricsjoo Yes, it works for all versions of VS 2022

@jwbats I should have mentioned it was a new separate extension. Sorry
